### PR TITLE
Add subestacions index on the manual

### PR DESCRIPTION
**Pull request by Xevib**

### CODE REVIEW

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_update_index_doc/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_update_index_doc/

**Comment by jaumef** [comment]
@Xevib I think we can close this PR, as in the new Material theme, all the headers show on the right side of the screen.

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_update_index_doc/

Things to review:
- [ ] Typos in Catalan
- [ ] Typos in Spanish
- [ ] Links routes in Spanish
- [ ] Links work in Catalan
- [ ] Links work in Spanish
- [ ] Images in Spanish
- [ ] Page index shows all headers

**Comment by jaumef** [comment]
Closing due to merge of #226

**Pull request closed without merging**
