### PR TITLE
Update image and description

### PR DESCRIPTION
**Pull request by Xevib**
### Description:

> Actualizar descargos

### Tasks:

- [x] Actualizar proces
- [ ] Actualizar traduciones

### Links:

* [NOM DEL FITXER EN CATALÀ #TÍTOL-A-REVISAR](http://builds.gisce.net/powerp-docs/powerp_<branch_name>/ca/<path/to/files>#<title-to-review>)
* [NOM DEL FITXER EN CASTELLÀ #TÍTOL-A-REVISAR](http://builds.gisce.net/powerp-docs/powerp_<branch_name>/es/<path/to/files>#<title-to-review>)

### CODE REVIEW

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_imp_desc/

Things to review:
- [ ] Typos in Catalan
- [ ] Typos in Spanish
- [ ] Links routes in Spanish
- [ ] Links work in Catalan
- [ ] Links work in Spanish
- [ ] Images in Spanish
- [ ] Page index shows all headers

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_imp_desc/

Things to review:
- [ ] Typos in Catalan
- [ ] Typos in Spanish
- [ ] Links routes in Spanish
- [ ] Links work in Catalan
- [ ] Links work in Spanish
- [ ] Images in Spanish
- [ ] Page index shows all headers

**Comment by jaumef** [comment]
Fer Merge amb `master` abans de continuar

**Comment by jaumef** [comment]
@Xevib està discontinuat? Tanquem la PR?

**Comment by jaumef** [comment]
@Xevib tanco la PR, ja que no m'has contestat i està molt endarrerida, si cal, torna a fer-la desde master.

**Pull request closed without merging**
