### PR TITLE
Fix 159 docs

### PR DESCRIPTION
**Pull request by jaumef**
### Description:

Actualizar la documentación del modelo 159 con nuevos enlaces e información de los procedimientos en caso de error.

### Tasks:

- [x] Translate
- [x] Add process description
- [x] Improve images and info of the model

### Links:

* [Comer → AdmPub → Informes](http://builds.gisce.net/powerp-docs/powerp_fix_159_docs/ca/comer/adm-pub/informes/#model-159)
* [Comer → AdmPub → Informes](http://builds.gisce.net/powerp-docs/powerp_fix_159_docs/es/comer/adm-pub/informes/#modelo-159)

### CODE REVIEW

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_fix_159_docs/

Things to review:
- [ ] Typos in Catalan
- [ ] Typos in Spanish
- [ ] Links routes in Spanish
- [ ] Links work in Catalan
- [ ] Links work in Spanish
- [ ] Images in Spanish
- [ ] Page index shows all headers

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_fix_159_docs/

Things to review:
- [ ] Typos in Catalan
- [ ] Typos in Spanish
- [ ] Links routes in Spanish
- [ ] Links work in Catalan
- [ ] Links work in Spanish
- [ ] Images in Spanish
- [ ] Page index shows all headers

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_fix_159_docs/

Things to review:
- [ ] Typos in Catalan
- [ ] Typos in Spanish
- [ ] Links routes in Spanish
- [ ] Links work in Catalan
- [ ] Links work in Spanish
- [ ] Images in Spanish
- [ ] Page index shows all headers

**Comment by jaumef** [comment]
@gisce/giscers Can someone review this?

**Comment by ecarreras** [comment]
Please resolve conflicts

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_fix_159_docs/

Things to review:
- [ ] Typos in Catalan
- [ ] Typos in Spanish
- [ ] Links routes in Spanish
- [ ] Links work in Catalan
- [ ] Links work in Spanish
- [ ] Images in Spanish
- [ ] Page index shows all headers

**Pull request merged**
