### PR TITLE
IMP Add ENDESA Jafre

### PR DESCRIPTION
**Pull request by tinogis**
### Description:

Adds ENDESA Jafre conversion

### Tasks:

- [ ] Tasks to do
- [x] Tasks done

### Links:

* [Apèndix#endesa-0031](http://builds.gisce.net/powerp-docs/powerp_ENDESA-Jafre/ca/base/GestionATR/apendice/#endesa-0031)
* [Apéndice#endesa-0031](http://builds.gisce.net/powerp-docs/powerp_ENDESA-Jafre/ca/base/GestionATR/apendice/#endesa-0031)

### CODE REVIEW

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_ENDESA-Jafre/

Things to review:
- [ ] Typos in Catalan
- [ ] Typos in Spanish
- [ ] Links routes in Spanish
- [ ] Links work in Catalan
- [ ] Links work in Spanish
- [ ] Images in Spanish
- [ ] Page index shows all headers

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_ENDESA-Jafre/

Things to review:
- [ ] Typos in Catalan
- [ ] Typos in Spanish
- [ ] Links routes in Spanish
- [ ] Links work in Catalan
- [ ] Links work in Spanish
- [ ] Images in Spanish
- [ ] Page index shows all headers

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_ENDESA-Jafre/

Things to review:
- [ ] Typos in Catalan
- [ ] Typos in Spanish
- [ ] Links routes in Spanish
- [ ] Links work in Catalan
- [ ] Links work in Spanish
- [ ] Images in Spanish
- [ ] Page index shows all headers

**Comment by jaumef** [comment]
(boyscout required) Some parts of the page like https://github.com/gisce/powerp-docs/pull/326/files#diff-146a8cf2f5fb0bbf97c0d36bc285b254R34 are not well translated

**Pull request merged**
