### PR TITLE
[NEW] CNAE Documentation

### PR DESCRIPTION
**Pull request by asimon91**
CNAE documentation have been added to PowERP Docs.

To do:

- [x] Translations
- [x] Fuzzy strings translations

### CODE REVIEW

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_cnae_docu/

**Comment by ecarreras** [comment]
A la documentació de les validacions de la CNMC fes-me referència

P.S.: Sent from a mobile phone, please excuse the brevity of the message

--
Eduard Carreras i Nadal
CTO
GISCE-TI, S.L.

El dia 27 gen. 2017 9:01 a. m., "Axel Simón González" <
notifications@github.com> va escriure:

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_cnae_docu/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_cnae_docu/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_cnae_docu/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_cnae_docu/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_cnae_docu/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_cnae_docu/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_cnae_docu/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_cnae_docu/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_cnae_docu/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_cnae_docu/

**Comment by ecarreras** [comment]
@asimon91 You have to resolve conflicts

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_cnae_docu/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_cnae_docu/

**Pull request merged**
