### PR TITLE
Update format for notes and other addons

### PR DESCRIPTION
**Pull request by jaumef**
### Description:

Updates the Notes of all files to use "admonition info" and a title.

### Tasks:

- [x] Refactor admonition notes to info adding the "Nota" title
- [x] Add title "Atenció" to admonition "Warning"
- [x] Add title "Consell" to admonition "Tip"
- [x] Translate nested notes
- [x] Check and remove index on docs

### Links:

Refactoring "Nota"  →  "Info"

image  →  image

* [Exemple de "Nota"](http://builds.gisce.net/powerp-docs/powerp_refactor_admonition_notes/ca/distri/calidad/terminos_y_definicion/#metodologia-per-la-obtencio-dinformacio-zonal-dinterrupcions-en-bt)
* [Ejemplo de "Nota"](http://builds.gisce.net/powerp-docs/powerp_refactor_admonition_notes/es/distri/calidad/terminos_y_definicion/#metodologia-para-la-obtencion-de-informacion-zonal-de-interrupciones-en-bt)

Adding "Atenció" to "Warnings"

image  →  image

* [Exemple de Warnings](http://builds.gisce.net/powerp-docs/powerp_refactor_admonition_notes/ca/comer/curvas/#creacio-de-nova-variable-de-configuracio)
* [Ejemplo de Warnings](http://builds.gisce.net/powerp-docs/powerp_refactor_admonition_notes/es/comer/curvas/#creacion-de-nueva-variable-de-configuracion)

Adding "Consell" to "Tip"

image  →  image

* [Exemple de Tip](http://builds.gisce.net/powerp-docs/powerp_refactor_admonition_notes/ca/comer/curvas/#creacio-de-nova-variable-de-configuracio)
* [Ejemplo de Tip](http://builds.gisce.net/powerp-docs/powerp_refactor_admonition_notes/es/comer/curvas/#creacion-de-nueva-variable-de-configuracion)

### CODE REVIEW

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_refactor_admonition_notes/

**Comment by ecarreras** [comment]
@jaumef you should merge the master branch here to get the result build using the material-ui template

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_refactor_admonition_notes/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_refactor_admonition_notes/

**Pull request merged**
