### PR TITLE
IMP Material Header colour

### LINKED ISSUE #262: Update base colour with CSS
Update the header colour with a CSS-specific colour: `#336699`

### PR DESCRIPTION
**Pull request by jaumef**
### Description:

Closes #262 

ADD Gisce Colour (#4D77A4) to the Tabs header

### Tasks:

- [x] Add new "site.css" file to change the header's css

### Links:

N/A - Any page

#### Before

image

#### After

image

### CODE REVIEW

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_imp_css_interface/

Things to review:
- [ ] Typos in Catalan
- [ ] Typos in Spanish
- [ ] Links routes in Spanish
- [ ] Links work in Catalan
- [ ] Links work in Spanish
- [ ] Images in Spanish
- [ ] Page index shows all headers

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_imp_css_interface/

Things to review:
- [ ] Typos in Catalan
- [ ] Typos in Spanish
- [ ] Links routes in Spanish
- [ ] Links work in Catalan
- [ ] Links work in Spanish
- [ ] Images in Spanish
- [ ] Page index shows all headers

**Comment by ecarreras** [comment]
Good! :+1: 

You should check the CSS in the menu when is a mobile device

image

**Comment by jaumef** [comment]
@gisce/giscers  Updated the CSS for low width resolution

image

image

image

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_imp_css_interface/

Things to review:
- [ ] Typos in Catalan
- [ ] Typos in Spanish
- [ ] Links routes in Spanish
- [ ] Links work in Catalan
- [ ] Links work in Spanish
- [ ] Images in Spanish
- [ ] Page index shows all headers

**Pull request merged**
