### PR TITLE
Doc import telemedida sql

### PR DESCRIPTION
**Pull request by MiquelIR**
### Description:

Add documentation to import telemeasures from mssql database

### Tasks:

- [x] Add first part of the documentation
- [ ] Complete the documentation once the module is finished

### Links:

* [contadores.md #Importació de telemesures](http://builds.gisce.net/powerp-docs/powerp_doc_import_telemedida_sql/ca/distri/contadores/#importacio-de-telemesures)
* [contadores.md #Importación de telemedidas](http://builds.gisce.net/powerp-docs/powerp_doc_import_telemedida_sql/es/distri/contadores/#importacio-de-telemesures)

### CODE REVIEW

**Comment by jaumef** [comment]
Fixed your test with #261 :+1:

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_doc_import_telemedida_sql/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_doc_import_telemedida_sql/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_doc_import_telemedida_sql/

**Pull request closed without merging**
