### PR TITLE
Some translations

### PR DESCRIPTION
**Pull request by ecarreras**
Progress in translations

### CODE REVIEW

**Comment by giscegit** [comment]
Documentation build URL:
ca_ES: http://builds.gisce.net/powerp-docs/ca/powerp_tranlations/es_ES: http://builds.gisce.net/powerp-docs/es/powerp_tranlations/

**Comment by giscegit** [comment]
Documentation build URL:
ca_ES: http://builds.gisce.net/powerp-docs/ca/powerp_tranlations/
es_ES: http://builds.gisce.net/powerp-docs/es/powerp_tranlations/

**Comment by giscegit** [comment]
Documentation build URL:
ca_ES: http://builds.gisce.net/powerp-docs/ca/powerp_tranlations/
es_ES: http://builds.gisce.net/powerp-docs/es/powerp_tranlations/

**Comment by giscegit** [comment]
Documentation build URL:
ca_ES: http://builds.gisce.net/powerp-docs/ca/powerp_tranlations/
es_ES: http://builds.gisce.net/powerp-docs/es/powerp_tranlations/

**Comment by giscegit** [comment]
Documentation build URL:
ca_ES: http://builds.gisce.net/powerp-docs/ca/powerp_tranlations/
es_ES: http://builds.gisce.net/powerp-docs/es/powerp_tranlations/

**Comment by giscegit** [comment]
Documentation build URL:
ca_ES: http://builds.gisce.net/powerp-docs/ca/powerp_tranlations/
es_ES: http://builds.gisce.net/powerp-docs/es/powerp_tranlations/

**Comment by giscegit** [comment]
Documentation build URL:
ca_ES: http://builds.gisce.net/powerp-docs/ca/powerp_tranlations/
es_ES: http://builds.gisce.net/powerp-docs/es/powerp_tranlations/

**Comment by ecarreras** [comment]
@tinogis si vols provar lo de mergejar traduccions ja fetes pots fer-ho a aquesta PR, pots mirar el test per veure si ha augmentat el percentatge de traducció

**Pull request merged**
