### PR TITLE
Fix translatable lists

### PR DESCRIPTION
**Pull request by jaumef**
Branch created to translate lists strings

- Requires Markdown-i18n to be updated (pending new version to update requirements.txt)
- Added strings from lists to pot and po files
- Added some translations

extra: moved check of strings in po from strings in pot before all strings translated test

### CODE REVIEW

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_fix_translatable_lists/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_fix_translatable_lists/

**Comment by ecarreras** [comment]
markdown-i18n v0.2.0 released

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_fix_translatable_lists/

**Pull request merged**
