### PR TITLE
Add images of TG info group and TG tab

### PR DESCRIPTION
**Pull request by MiquelIR**

### CODE REVIEW

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_images_TG_meters/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_images_TG_meters/

**Comment by ecarreras** [comment]
Falta la nova funcionalitat que has afegit del checkbox

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_images_TG_meters/

**Comment by ecarreras** [comment]
Update your branch from master

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_images_TG_meters/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_images_TG_meters/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_images_TG_meters/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_images_TG_meters/

**Pull request merged**
