### PR TITLE
Improve Notificaciones ATR

### LINKED ISSUE #281: Actualitzar documentació de notificacions ATR
Les notificacions ATR estan canviant.

Cal afegir els nous canvis i eliminar documentació "incorrecta" que ha quedat obsoleta amb els nous canvis.

### PR DESCRIPTION
**Pull request by jaumef**
### Description:

Closes #281 
Improves docs of `Base>GestiónATR>Notificaciones` with the new changes on OpenERP.

### Tasks:

- [x] Add changes of "activar canvis"
- [x] Add changes of "Notificacio Rebuigs"
- [x] Update GestionATR docs files to be in es_ES
- [x] Translate ALL

### Links:

* [Base → Gestió ATR → Notificacions](http://builds.gisce.net/powerp-docs/powerp_imp_atr_notify/ca/base/GestionATR/notificaciones/)
* [Base → Gestión ATR → Notificaciones](http://builds.gisce.net/powerp-docs/powerp_imp_atr_notify/es/base/GestionATR/notificaciones/)

### CODE REVIEW

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_imp_atr_notify/

Things to review:
- [ ] Typos in Catalan
- [ ] Typos in Spanish
- [ ] Links routes in Spanish
- [ ] Links work in Catalan
- [ ] Links work in Spanish
- [ ] Images in Spanish
- [ ] Page index shows all headers

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_imp_atr_notify/

Things to review:
- [ ] Typos in Catalan
- [ ] Typos in Spanish
- [ ] Links routes in Spanish
- [ ] Links work in Catalan
- [ ] Links work in Spanish
- [ ] Images in Spanish
- [ ] Page index shows all headers

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_imp_atr_notify/

Things to review:
- [ ] Typos in Catalan
- [ ] Typos in Spanish
- [ ] Links routes in Spanish
- [ ] Links work in Catalan
- [ ] Links work in Spanish
- [ ] Images in Spanish
- [ ] Page index shows all headers

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_imp_atr_notify/

Things to review:
- [ ] Typos in Catalan
- [ ] Typos in Spanish
- [ ] Links routes in Spanish
- [ ] Links work in Catalan
- [ ] Links work in Spanish
- [ ] Images in Spanish
- [ ] Page index shows all headers

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_imp_atr_notify/

Things to review:
- [ ] Typos in Catalan
- [ ] Typos in Spanish
- [ ] Links routes in Spanish
- [ ] Links work in Catalan
- [ ] Links work in Spanish
- [ ] Images in Spanish
- [ ] Page index shows all headers

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_imp_atr_notify/

Things to review:
- [ ] Typos in Catalan
- [ ] Typos in Spanish
- [ ] Links routes in Spanish
- [ ] Links work in Catalan
- [ ] Links work in Spanish
- [ ] Images in Spanish
- [ ] Page index shows all headers

**Comment by jaumef** [comment]
@gisce/giscers Can someone review this?

**Comment by ecarreras** [comment]
> @gisce/giscers Can someone review this?

I think you should review this with the team which have made the specifications

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_imp_atr_notify/

Things to review:
- [ ] Typos in Catalan
- [ ] Typos in Spanish
- [ ] Links routes in Spanish
- [ ] Links work in Catalan
- [ ] Links work in Spanish
- [ ] Images in Spanish
- [ ] Page index shows all headers

**Comment by jaumef** [comment]
@eberloso updated!

**Pull request merged**
