### PR TITLE
Fix the "Criteri Estado" entry on the doc.

### PR DESCRIPTION
**Pull request by AdriNicolau**
### Description:
* Fixed the "Criteri Estado" entry for each file of the 4666 to be correct.

### Tasks:

- [x] Fix all the reference of the 4131 to the 4666

### Links:

> docs/distri/adm-pub/resoluciones/4666.md

* [4666 - CA](http://builds.gisce.net/powerp-docs/powerp_fix_4666_documentation/ca/distri/adm-pub/resoluciones/4666/)
* [4666 - ES](http://builds.gisce.net/powerp-docs/powerp_fix_4666_documentation/es/distri/adm-pub/resoluciones/4666/)

### CODE REVIEW

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_fix_4666_documentation/

Things to review:
- [ ] Typos in Catalan
- [ ] Typos in Spanish
- [ ] Links routes in Spanish
- [ ] Links work in Catalan
- [ ] Links work in Spanish
- [ ] Images in Spanish
- [ ] Page index shows all headers

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_fix_4666_documentation/

Things to review:
- [ ] Typos in Catalan
- [ ] Typos in Spanish
- [ ] Links routes in Spanish
- [ ] Links work in Catalan
- [ ] Links work in Spanish
- [ ] Images in Spanish
- [ ] Page index shows all headers

**Comment by jaumef** [comment]
@AdriNicolau merge and we're done :+1:

**Comment by jaumef** [comment]
bug → it doesn't work (build issues)

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_fix_4666_documentation/

Things to review:
- [ ] Typos in Catalan
- [ ] Typos in Spanish
- [ ] Links routes in Spanish
- [ ] Links work in Catalan
- [ ] Links work in Spanish
- [ ] Images in Spanish
- [ ] Page index shows all headers

**Pull request merged**
