### PR TITLE
Change theme to material

### LINKED ISSUE #211: Provar tema material-design
http://squidfunk.github.io/mkdocs-material/

### PR DESCRIPTION
**Pull request by jaumef**
Closes #211 

### Description:

Update the theme used by mkdocs to Material

### Tasks:

- [x] Update the theme in mkdocs.yml files
- [x] Add requirement for mkdocs-material

### Links:

No links needed, just use the default link

### CODE REVIEW

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_change_theme_to_material/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_change_theme_to_material/

**Comment by gdalmau** [comment]
:cake:

**Comment by MiquelIR** [comment]
:cake:

**Comment by francescpuig7** [comment]
:zap:

**Comment by gdalmau** [comment]
You can check the following things to add:

- Change primary and accent colors to GISCE colors http://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
```
extra:
  palette:
    primary: 'blue'
    accent: 'blue'
```
- Add favicon http://squidfunk.github.io/mkdocs-material/getting-started/#adding-a-favicon
- Check the localization l18n http://squidfunk.github.io/mkdocs-material/getting-started/#localization

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_change_theme_to_material/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_change_theme_to_material/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_change_theme_to_material/

**Pull request merged**
