### PR TITLE
[NEW] AEAT 347 model documentation

### PR DESCRIPTION
**Pull request by asimon91**
This PR adds the documentation for AEAT 347 model generation module.

To do:

- [x] Translations

### CODE REVIEW

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_347_docu/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_347_docu/

**Comment by ecarreras** [comment]
Update your branch from master

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_347_docu/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_347_docu/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_347_docu/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_347_docu/

**Pull request merged**
