### PR TITLE
New wizard avancar facturacio

### PR DESCRIPTION
**Pull request by gdalmau**
This PR adds documentation to wizard_avancar_facturacio

### CODE REVIEW

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_wizard_avancar_facturacio/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_wizard_avancar_facturacio/

**Comment by giscegit** [comment]
Documentation build URL:
http://builds.gisce.net/powerp-docs/powerp_new_wizard_avancar_facturacio/

**Comment by ecarreras** [comment]
@gdalmau les captures de pantalla millor en castellà

**Pull request merged**
